altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  111a17b5-3c7e-464d-a51e-6c9148589058:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-14T17:13:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8c40efaa-1988-4d07-825b-47643a44dcff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f716931a-5493-4851-a447-8cfa88375b4b
        userCondition: null
fs: filesystem
handle: messagingUploads
name: 'Messaging Uploads'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
