dateModified: 1752416535
email:
  fromEmail: ethan@brackstone.dev
  fromName: craft-messages
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5b3c6a14-96b0-4852-94cc-124d03e58002: Profiles # Profiles
    46df7a68-b0e9-404c-8dfc-9e6a6c1f6940: 'Public Schema' # Public Schema
    495efd84-b676-4e29-8d16-ba1680d57f6a: email # email
    655859bb-176c-4170-a470-32c339ba3353: 'First Name' # First Name
    b2c3a698-8ad6-4918-a120-1cebb04a4761: craft-messages # craft-messages
    cf8719db-dc0c-4545-ae34-514aec0b90fb: Profiles # Profiles
    f74b1bd9-9820-4257-8ac8-dc12b206f8b6: craft-messages # craft-messages
    fa7f09e7-90ba-42e2-817a-6a9c7ded99b0: 'Last Name' # Last Name
system:
  edition: solo
  live: true
  name: craft-messages
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
